services:
  telegram-mega-rename-bot:
    build:
      type: dockerfile
      dockerfile: ./deploy/Dockerfile.prod
    deployment:
      port: 8000
    env:
      - name: TELEGRAM_BOT_TOKEN
        value: "7777154511:AAFCwcTQ1zHDRL2SNRGNOxv1SNuz8NzYVDo"
